### ISSUE TITLE
Ask for advice

### ISSUE THREAD

**Issue by zhibin-chen** [rubyhan1314/BitcoinForJava#1]
First,  thank you for your project that I can learn from.

Process, I found: 
part5_Tracsaction show error : com.esotericsoftware.kryo.KryoException:java.lang.IndexOutOfBoundsException: Index: 46, Size: 2. 

Can you see it, please? Thanks.

**Comment by zhibin-chen** [comment]
com.esotericsoftware.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 46, Size: 2
Serialization trace:
prevBlockHash (cldy.hanru.blockchain.block.Block)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at cldy.hanru.blockchain.util.SerializeUtils.deserialize(SerializeUtils.java:33)
	at cldy.hanru.blockchain.store.RocksDBUtils.getBlock(RocksDBUtils.java:117)
	at cldy.hanru.blockchain.block.Blockchain$BlockchainIterator.hashNext(Blockchain.java:110)
	at cldy.hanru.blockchain.block.Blockchain.getAllSpentTXOs(Blockchain.java:172)
	at cldy.hanru.blockchain.block.Blockchain.findUnspentTransactions(Blockchain.java:203)
	at cldy.hanru.blockchain.block.Blockchain.findUTXO(Blockchain.java:237)
	at cldy.hanru.blockchain.cli.CLI.getBalance(CLI.java:204)
	at cldy.hanru.blockchain.cli.CLI.run(CLI.java:89)
	at cldy.hanru.blockchain.Main.main(Main.java:18)
Caused by: java.lang.IndexOutOfBoundsException: Index: 46, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:857)
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:780)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
	... 11 more

Process finished with exit code 0

**Comment by rubyhan1314** [comment]
你能贴一下区块的信息吗？还有就是运行交易的命令

**Comment by rubyhan1314** [comment]
运行printchain就行

**Comment by zhibin-chen** [comment]
已解决，谢谢啦
